@startuml

title __BEAN's Class Diagram__\n

  namespace com.aaron.yespdf {
    namespace common {
      namespace bean {
        class com.aaron.yespdf.common.bean.Collection {
            {static} + CREATOR : Creator<Collection>
            ~ id : Long
            ~ name : String
            + Collection()
            + Collection()
            + Collection()
            + describeContents()
            + getId()
            + getName()
            + setId()
            + setName()
            + toString()
            + writeToParcel()
            # Collection()
        }
      }
    }
  }
  

  namespace com.aaron.yespdf {
    namespace common {
      namespace bean {
        class com.aaron.yespdf.common.bean.PDF {
            {static} + CREATOR : Creator<PDF>
            ~ bookmark : String
            ~ cover : String
            ~ curPage : int
            ~ dir : String
            ~ id : Long
            ~ latestRead : long
            ~ name : String
            ~ path : String
            ~ progress : String
            ~ totalPage : int
            + PDF()
            + PDF()
            + describeContents()
            + getBookmark()
            + getCover()
            + getCurPage()
            + getDir()
            + getId()
            + getLatestRead()
            + getName()
            + getPath()
            + getProgress()
            + getTotalPage()
            + setBookmark()
            + setCover()
            + setCurPage()
            + setDir()
            + setId()
            + setLatestRead()
            + setName()
            + setPath()
            + setProgress()
            + setTotalPage()
            + toString()
            + writeToParcel()
            # PDF()
        }
      }
    }
  }
  

  namespace com.aaron.yespdf {
    namespace common {
      namespace bean {
        class com.aaron.yespdf.common.bean.RecentPDF {
            {static} + CREATOR : Creator<RecentPDF>
            ~ dir : String
            ~ id : Long
            ~ name : String
            + RecentPDF()
            + RecentPDF()
            + RecentPDF()
            + describeContents()
            + getDir()
            + getId()
            + getName()
            + setDir()
            + setId()
            + setName()
            + toString()
            + writeToParcel()
            # RecentPDF()
        }
      }
    }
  }
  

  com.aaron.yespdf.common.bean.Collection .up.|> android.os.Parcelable
  com.aaron.yespdf.common.bean.PDF .up.|> android.os.Parcelable
  com.aaron.yespdf.common.bean.RecentPDF .up.|> android.os.Parcelable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
