@startuml

title __SOURCE's Class Diagram__\n

  namespace com.github.barteksc.pdfviewer {
    namespace source {
      class com.github.barteksc.pdfviewer.source.AssetSource {
          - assetName : String
          + AssetSource()
          + createDocument()
      }
    }
  }
  

  namespace com.github.barteksc.pdfviewer {
    namespace source {
      class com.github.barteksc.pdfviewer.source.ByteArraySource {
          - data : byte[]
          + ByteArraySource()
          + createDocument()
      }
    }
  }
  

  namespace com.github.barteksc.pdfviewer {
    namespace source {
      interface com.github.barteksc.pdfviewer.source.DocumentSource {
          {abstract} + createDocument()
      }
    }
  }
  

  namespace com.github.barteksc.pdfviewer {
    namespace source {
      class com.github.barteksc.pdfviewer.source.FileSource {
          - file : File
          + FileSource()
          + createDocument()
      }
    }
  }
  

  namespace com.github.barteksc.pdfviewer {
    namespace source {
      class com.github.barteksc.pdfviewer.source.InputStreamSource {
          - inputStream : InputStream
          + InputStreamSource()
          + createDocument()
      }
    }
  }
  

  namespace com.github.barteksc.pdfviewer {
    namespace source {
      class com.github.barteksc.pdfviewer.source.UriSource {
          - uri : Uri
          + UriSource()
          + createDocument()
      }
    }
  }
  

  com.github.barteksc.pdfviewer.source.AssetSource .up.|> com.github.barteksc.pdfviewer.source.DocumentSource
  com.github.barteksc.pdfviewer.source.ByteArraySource .up.|> com.github.barteksc.pdfviewer.source.DocumentSource
  com.github.barteksc.pdfviewer.source.FileSource .up.|> com.github.barteksc.pdfviewer.source.DocumentSource
  com.github.barteksc.pdfviewer.source.InputStreamSource .up.|> com.github.barteksc.pdfviewer.source.DocumentSource
  com.github.barteksc.pdfviewer.source.UriSource .up.|> com.github.barteksc.pdfviewer.source.DocumentSource


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
