@startuml

title __SCROLL's Class Diagram__\n

  namespace com.github.barteksc.pdfviewer {
    namespace scroll {
      class com.github.barteksc.pdfviewer.scroll.DefaultScrollHandle {
          # context : Context
          # textView : TextView
          {static} - DEFAULT_TEXT_SIZE : int
          {static} - HANDLE_LONG : int
          {static} - HANDLE_SHORT : int
          - currentPos : float
          - handler : Handler
          - hidePageScrollerRunnable : Runnable
          - inverted : boolean
          - relativeHandlerMiddle : float
          + DefaultScrollHandle()
          + DefaultScrollHandle()
          + destroyLayout()
          + hide()
          + hideDelayed()
          + onTouchEvent()
          + setPageNum()
          + setScroll()
          + setTextColor()
          + setTextSize()
          + setupLayout()
          + show()
          + shown()
          - calculateMiddle()
          - isPDFViewReady()
          - setPosition()
      }
    }
  }
  

  namespace com.github.barteksc.pdfviewer {
    namespace scroll {
      interface com.github.barteksc.pdfviewer.scroll.ScrollHandle {
          {abstract} + destroyLayout()
          {abstract} + hide()
          {abstract} + hideDelayed()
          {abstract} + setPageNum()
          {abstract} + setScroll()
          {abstract} + setupLayout()
          {abstract} + show()
          {abstract} + shown()
      }
    }
  }
  

  com.github.barteksc.pdfviewer.scroll.DefaultScrollHandle .up.|> com.github.barteksc.pdfviewer.scroll.ScrollHandle
  com.github.barteksc.pdfviewer.scroll.DefaultScrollHandle -up-|> android.widget.RelativeLayout
  com.github.barteksc.pdfviewer.scroll.DefaultScrollHandle o-- com.github.barteksc.pdfviewer.PDFView : pdfView


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
