@startuml

title __UTIL's Class Diagram__\n

  namespace com.github.barteksc.pdfviewer {
    namespace util {
      class com.github.barteksc.pdfviewer.util.ArrayUtils {
          {static} + arrayToString()
          {static} + calculateIndexesInDuplicateArray()
          {static} + deleteDuplicatedPages()
          - ArrayUtils()
      }
    }
  }
  

  namespace com.github.barteksc.pdfviewer {
    namespace util {
      class com.github.barteksc.pdfviewer.util.Constants {
          {static} + DEBUG_MODE : boolean
          {static} + PART_SIZE : float
          {static} + PRELOAD_OFFSET : int
          {static} + THUMBNAIL_RATIO : float
      }
    }
  }
  

  namespace com.github.barteksc.pdfviewer {
    namespace util {
      class com.github.barteksc.pdfviewer.util.Constants.Cache {
          {static} + CACHE_SIZE : int
          {static} + THUMBNAILS_CACHE_SIZE : int
      }
    }
  }
  

  namespace com.github.barteksc.pdfviewer {
    namespace util {
      class com.github.barteksc.pdfviewer.util.Constants.Pinch {
          {static} + MAXIMUM_ZOOM : float
          {static} + MINIMUM_ZOOM : float
      }
    }
  }
  

  namespace com.github.barteksc.pdfviewer {
    namespace util {
      class com.github.barteksc.pdfviewer.util.FileUtils {
          {static} + copy()
          {static} + fileFromAsset()
          - FileUtils()
      }
    }
  }
  

  namespace com.github.barteksc.pdfviewer {
    namespace util {
      enum FitPolicy {
        BOTH
        HEIGHT
        WIDTH
      }
    }
  }
  

  namespace com.github.barteksc.pdfviewer {
    namespace util {
      class com.github.barteksc.pdfviewer.util.MathUtils {
          {static} - BIG_ENOUGH_CEIL : double
          {static} - BIG_ENOUGH_FLOOR : double
          {static} - BIG_ENOUGH_INT : int
          {static} + ceil()
          {static} + floor()
          {static} + limit()
          {static} + limit()
          {static} + max()
          {static} + max()
          {static} + min()
          {static} + min()
          - MathUtils()
      }
    }
  }
  

  namespace com.github.barteksc.pdfviewer {
    namespace util {
      class com.github.barteksc.pdfviewer.util.PageSizeCalculator {
          - fitEachPage : boolean
          - heightRatio : float
          - optimalMaxHeightPageSize : SizeF
          - optimalMaxWidthPageSize : SizeF
          - originalMaxHeightPageSize : Size
          - originalMaxWidthPageSize : Size
          - viewSize : Size
          - widthRatio : float
          + PageSizeCalculator()
          + calculate()
          + getOptimalMaxHeightPageSize()
          + getOptimalMaxWidthPageSize()
          - calculateMaxPages()
          - fitBoth()
          - fitHeight()
          - fitWidth()
      }
    }
  }
  

  namespace com.github.barteksc.pdfviewer {
    namespace util {
      enum SnapEdge {
        CENTER
        END
        NONE
        START
      }
    }
  }
  

  namespace com.github.barteksc.pdfviewer {
    namespace util {
      class com.github.barteksc.pdfviewer.util.Util {
          {static} - DEFAULT_BUFFER_SIZE : int
          {static} + getDP()
          {static} + toByteArray()
      }
    }
  }
  

  com.github.barteksc.pdfviewer.util.Constants +-down- com.github.barteksc.pdfviewer.util.Constants.Cache
  com.github.barteksc.pdfviewer.util.Constants +-down- com.github.barteksc.pdfviewer.util.Constants.Pinch
  com.github.barteksc.pdfviewer.util.PageSizeCalculator o-- com.github.barteksc.pdfviewer.util.FitPolicy : fitPolicy


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
